name: A workflow to build an application

on:
    push:
        branches: [ main ]

jobs:
    debug-build:
        name: Build a debug version of the app
        runs-on: ubuntu-latest

        steps:
        - name: Checkout source code
          uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x

        - name: Restore dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build -c debug --no-restore

        - name: Run it for fun
          run: dotnet bin/Debug/net8.0/Hello_Github_Actions.dll

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4
          with:
            # Artifact name
            name: HelloWorldDebug # .zip will be added automatically
            path: bin/Debug/net8.0/*.*

    release-build:
        needs: debug-build
        name: Build a release version of the app
        runs-on: ubuntu-latest

        steps:
        - name: Checkout source code
          uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x

        - name: Restore dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build -c release --no-restore

        - name: Run it for fun
          run: dotnet bin/Release/net8.0/Hello_Github_Actions.dll

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4
          with:
            # Artifact name
            name: HelloWorldRelease # .zip will be added automatically
            path: bin/Release/net8.0/*.*