name: A workflow to build an application

on:
    push:
        branches: [ main ]

jobs:
    build:
        name: Build the app
        runs-on: ubuntu-latest

        steps:
        - name: Checkout source code
          uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x

        - name: Restore dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build -c release --no-restore

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4
          with:
            # Artifact name
            name: GitHubActionsHelloWorldConsoleDownloadableArtifact # .zip will be added automatically
            path: bin/Release/net8.0/*.*

        - name: check pwd
          run: pwd